// * 1. Sự kiện là gì ? (event)
// * 2. Thêm 1 sự kiện: selector.addEventListener("eventName", handler, [options])
// * 3. Click, keydown, keypress, keyup, ...
// * 4. Mouseover, mousemove, mouseleave, onload, DOMContentLoad,...
